version: 2

sources:
  - name: clockin
    database: "{{ target.project }}"
    schema: "{{ target.dataset }}"

    quoting:
      database: true
      schema: true
      identifier: true

    loader: 2C
    loaded_at_field: _ingestionDateTime

    freshness:
      warn_after: {count: 30, period: day}
      error_after: {count: 90, period: day}

    tables:

      - name: clockinrecords 
        identifier: clockinrecords
        columns:
          - name: devicecode
            tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_not_be_null
              - is_valid_device

          - name: mdmeventdate
            tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_not_be_null

          - name: mdmpersonid
            tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_not_be_null
              - is_valid_employee

          - name: nsrcode
            tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_not_be_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  inclusive: false

      - name: employee 
        identifier: employee
        columns:
          - name: mdmpersonid
            tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_not_be_null

          - name: mdmname
            tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_not_be_null

          - name: dataadmissao
            tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_not_be_null

      - name: mdmcompany 
        identifier: mdmcompany
        columns:
          - name: mdmname
            tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_not_be_null

          - name: mdmtaxid
            tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_not_be_null
              - is_valid_taxid
